### DISCUSSION TITLE
Home Assistant Integration

### DISCUSSION THREAD

**Discussion by ojarosch** [pixelit-project/PixelIt#190] [General]
Integration Snippets für Home Assistant

**Comment by ojarosch** [comment]
sleepMode Switch

https://www.home-assistant.io/integrations/switch.rest/

```
switch:
  - platform: rest
    name: Pixel It
    method: post
    resource: http://<hostname>/api/screen
    state_resource: http://<hostname>/api/matrixinfo
    body_on: '{"sleepMode": false}'
    body_off: '{"sleepMode": true}'
    is_on_template: "{{ not value_json.sleepMode }}"
```
