### DISCUSSION TITLE
Clock color control as HA light

### DISCUSSION THREAD

**Discussion by sjthespian** [pixelit-project/PixelIt#271] [Node-RED Flows]
This is a flow plus some snippets of HA config that allow me to control the color of the PixelIT clock via. Home Assistant by treating it as a light. It requires that you have your PixelIT set up with MQTT and HA set for discovery. In my case, the discovered device is named `light.pixelit`.

The only drawback to doing it this way is that the color will not update until the next time the clock refreshes. I don't know of a way to make it change immediately.

HA Templates:
```yaml
# Virtual light for pixelit clock
light:
- platform: template
  lights:
    pixelit_clock:
      friendly_name: PixelIt Clock
      unique_id: pixelit_clock
      level_template: "{{ state_attr('light.pixelit', 'brightness')|int }}"
      value_template: "{{ states('light.pixelit') }}"
      color_template: "({{states('input_number.pixelit_hue') | int}}, {{states('input_number.pixelit_sat') | int}})"
      set_level:
        service: light.turn_on
        target:
          entity_id: light.pixelit
        data:
          brightness: "{{ brightness }}"
      set_color:
        - service: input_number.set_value
          data:
            value: "{{ h }}"
            entity_id: input_number.pixelit_hue
        - service: input_number.set_value
          data:
            value: "{{ s }}"
            entity_id: input_number.pixelit_sat
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.pixelit
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.pixelit

# Fake inputs for PixelIt color
input_number:
  pixelit_hue:
    min: 0
    max: 360
    initial: 305
  pixelit_sat:
    min: 0
    max: 100
    initial: 100
```

And the flow that maps the above inputs to the clock color:

![Clock color flow](https://user-images.githubusercontent.com/1789285/227360995-57365b66-3488-4a8f-9661-e47cd571be82.png)

```json
[{"id":"9be29ff02854af4a","type":"Screen Data Update","z":"85e0e0f6f805191a","name":"Screen Data Update","x":1180,"y":340,"wires":[["d3b801f1717d16b5"]]},{"id":"143b978220b32ffa","type":"comment","z":"85e0e0f6f805191a","name":"Internal PixelIt Clock [internal_clock]","info":"","x":140,"y":300,"wires":[]},{"id":"8b9a8cd55e7e020e","type":"inject","z":"85e0e0f6f805191a","name":"Init","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.1","topic":"","payload":"","payloadType":"date","x":70,"y":340,"wires":[["efbf1891f55eb57f"]]},{"id":"8e6a4b1443c4d89f","type":"Screen Init","z":"85e0e0f6f805191a","name":"Screen Init","inscreenName":"internal_clock","induration":"300","x":570,"y":340,"wires":[["76527b79dab7c7e0"]]},{"id":"76527b79dab7c7e0","type":"Switch Animation","z":"85e0e0f6f805191a","name":"Switch Animation","aktiv":"true","animation":"fade","indata":"","inwidth":"","incolorHex":"","incolorR":"","incolorG":"","incolorB":"","x":790,"y":340,"wires":[["4990f1344c2f7748"]]},{"id":"4990f1344c2f7748","type":"Clock","z":"85e0e0f6f805191a","name":"Clock","inswitchAktiv":"false","inswitchSec":"15","inwithSeconds":"false","incolorHex":"{{color}}","incolorR":"","incolorG":"","incolorB":"","x":990,"y":340,"wires":[["9be29ff02854af4a"]]},{"id":"efbf1891f55eb57f","type":"function","z":"85e0e0f6f805191a","name":"Set clock color","func":"function componentToHex(c) {\n    var hex = c.toString(16);\n    return hex.length == 1 ? \"0\" + hex : hex;\n}\n\nfunction rgbToHex(r, g, b) {\n    return componentToHex(r) + componentToHex(g) + componentToHex(b);\n}\nmsg.color = rgbToHex(msg.payload.red, msg.payload.green, msg.payload.blue);\nnode.status({ fill: 'green', shape: 'ring', text: msg.color});\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":340,"wires":[["8e6a4b1443c4d89f"]]},{"id":"d3b801f1717d16b5","type":"Core","z":"85e0e0f6f805191a","name":"Core","ip":"pixelit01.lapseofthought.com","masterTopic":"","x":1410,"y":340,"wires":[[]]},{"id":"9701d4a1010aedd9","type":"comment","z":"85e0e0f6f805191a","name":"Clock Color Setup","info":"","x":90,"y":420,"wires":[]},{"id":"4fac4f6973ce491e","type":"server-state-changed","z":"85e0e0f6f805191a","name":"Pixelit Hue Select","server":"a54a6202.f4317","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_number.pixelit_hue","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":"0","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":100,"y":460,"wires":[["d3be045651a672d0"]]},{"id":"7d95ea95fee6d59e","type":"server-state-changed","z":"85e0e0f6f805191a","name":"Pixelit Saturation Select","server":"a54a6202.f4317","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_number.pixelit_sat","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":"0","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":120,"y":520,"wires":[["f299305927adeb32"]]},{"id":"f299305927adeb32","type":"function","z":"85e0e0f6f805191a","name":"Set Sat Var","func":"flow.set('pixelit_sat', msg.payload)\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":350,"y":520,"wires":[["e94bcdb1e05a3601"]]},{"id":"d3be045651a672d0","type":"function","z":"85e0e0f6f805191a","name":"Set Hue Var","func":"flow.set('pixelit_hue', msg.payload)\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":350,"y":460,"wires":[["e94bcdb1e05a3601"]]},{"id":"e94bcdb1e05a3601","type":"function","z":"85e0e0f6f805191a","name":"Input to Array","func":"var HSVarray = [ flow.get('pixelit_hue'), flow.get('pixelit_sat'), 100 ];\nmsg.payload = HSVarray;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":540,"y":460,"wires":[["5dd48b6e6a9a9390"]]},{"id":"5dd48b6e6a9a9390","type":"color-convert","z":"85e0e0f6f805191a","input":"hsv","output":"rgb","outputType":"object","scaleInput":false,"x":730,"y":460,"wires":[["efbf1891f55eb57f"]]},{"id":"a54a6202.f4317","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
```
